[package]
name = "mh_z1911a"
Version = "0.1.0"
authors = ["Eric Lockman <eric@xealstudios.com>"]
edition = "2021"

[dependencies]
serialport = "4.0"
tokio = { version = "1", features = ["full"] }
